### ISSUE TITLE
Variance instead of sd passed in the definition of the function dmr

### ISSUE THREAD

**Issue by b-klaus** [mikelove/asthma#2]
Hi Mike,

thank you for your interesting thoughts on power analysis! 

In the definition of the function  dmr,  you use the estimated log (dispersions)' prior **variance** 0.28:

_dmr <- function(x) (.05 + 2.06 / x) * exp(rnorm(length(x),0,.28))_

to scatter the dispersions used for simulation around their expected values from the 
dispersion fit 

However as _rnorm_ accepts **standard deviation** as the second parameter, shouldn't that read

_dmr <- function(x) (.05 + 2.06 / x) * exp(rnorm(length(x),sqrt(0,.28)))_

? 

Thanks and best wishes,

Bernd

**Comment by mikelove** [comment]
you're right. i'll fix this bug and re-knit!

**Comment by mikelove** [comment]
ok, I fixed this bug, thanks again

https://github.com/mikelove/asthma/commit/d18ee8f97a41bb0db29df2ea957084e457e6ed23
